# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 781f3f9775e24173deb0ccb312292e5970f1d690fd1775aae0f4274efcb5a6665bcc36c0a34df2db8b37421b254a6b21299b7d816f1c28537273091a39b7b5ce

test:
  secret_key_base: 7e7eaedf25d5e6a4b19f16032ffbfa364b3469e13cf1d4c5093755d0b1e724b9cea5671ca4199d08cafe1dd733bbb2d4a23dea463ceff091ee410058d30980ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
